### ISSUE TITLE
No web UI login page after TRAINS server installation (0.16.0)

### ISSUE THREAD

**Issue by apwojcik** [allegroai/trains#192]
I have installed the TRAINS server version 0.16.0 on a newly build Linux server. Previously I was using 0.15.1, and it was working with no issues. However, the new installation has no login page. The only page has example projects and experiments.
I followed the Trains Server Troubleshooting section "Why is web login authentication not working?" but it didn't solve the issue.
Below is the `apiserver.log`.
```
[2020-08-20 02:31:46,726] [8] [INFO] [trains.es_factory] Using override elastic host elasticsearch
[2020-08-20 02:31:46,727] [8] [INFO] [trains.es_factory] Using override elastic port 9200
[2020-08-20 02:31:46,992] [8] [INFO] [trains.redis_manager] Using override redis host redis
[2020-08-20 02:31:46,992] [8] [INFO] [trains.redis_manager] Using override redis port 6379
[2020-08-20 02:31:47,081] [8] [WARNING] [trains.schema] failed loading cache: [Errno 2] No such file or directory: '/opt/trains/server/schema/services/_cache.json'
[2020-08-20 02:31:47,081] [8] [INFO] [trains.schema] regenerating schema cache
[2020-08-20 02:31:49,679] [8] [INFO] [trains.server] ################ API Server initializing #####################
[2020-08-20 02:31:49,679] [8] [INFO] [trains.database] Initializing database connections
[2020-08-20 02:31:49,680] [8] [INFO] [trains.database] Using override mongodb host mongo
[2020-08-20 02:31:49,680] [8] [INFO] [trains.database] Using override mongodb port 27017
[2020-08-20 02:31:49,681] [8] [INFO] [trains.database] Registering connection to auth-db (mongodb://mongo:27017/auth)
[2020-08-20 02:31:49,682] [8] [INFO] [trains.database] Registering connection to backend-db (mongodb://mongo:27017/backend)
[2020-08-20 02:31:49,684] [8] [WARNING] [elasticsearch] GET http://elasticsearch:9200/_template/events* [status:N/A request:0.001s]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 233, in perform_request
    method, url, body, retries=Retry(False), headers=request_headers, **kw
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 727, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 379, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.6/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib64/python3.6/http/client.py", line 1254, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1300, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1249, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.6/http/client.py", line 974, in send
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 187, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 172, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fd4ec93f208>: Failed to establish a new connection: [Errno 111] Connection refused
[2020-08-20 02:31:49,687] [8] [WARNING] [elasticsearch] GET http://elasticsearch:9200/_template/events* [status:N/A request:0.001s]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 233, in perform_request
    method, url, body, retries=Retry(False), headers=request_headers, **kw
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 727, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 379, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.6/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib64/python3.6/http/client.py", line 1254, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1300, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1249, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.6/http/client.py", line 974, in send
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 187, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 172, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fd4ec93f2e8>: Failed to establish a new connection: [Errno 111] Connection refused
[2020-08-20 02:31:49,688] [8] [WARNING] [elasticsearch] GET http://elasticsearch:9200/_template/events* [status:N/A request:0.001s]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 233, in perform_request
    method, url, body, retries=Retry(False), headers=request_headers, **kw
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 727, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 379, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.6/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib64/python3.6/http/client.py", line 1254, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1300, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1249, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.6/http/client.py", line 974, in send
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 187, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 172, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fd4ec93f3c8>: Failed to establish a new connection: [Errno 111] Connection refused
[2020-08-20 02:31:49,690] [8] [WARNING] [elasticsearch] GET http://elasticsearch:9200/_template/events* [status:N/A request:0.001s]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 233, in perform_request
    method, url, body, retries=Retry(False), headers=request_headers, **kw
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 727, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 379, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.6/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib64/python3.6/http/client.py", line 1254, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1300, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1249, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.6/http/client.py", line 974, in send
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 187, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 172, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fd4ec93f4e0>: Failed to establish a new connection: [Errno 111] Connection refused
[2020-08-20 02:31:49,690] [8] [WARNING] [trains.initialize] Could not connect to es server. Retry 1 of 4. Waiting for 30sec
[2020-08-20 02:32:19,796] [8] [INFO] [trains.initialize] Applying mappings to ES host: [ConfigTree([('host', 'elasticsearch'), ('port', '9200')])]
[2020-08-20 02:32:19,932] [8] [INFO] [trains.initialize] [{'mapping': 'events_log', 'result': {'acknowledged': True}}, {'mapping': 'events_plot', 'result': {'acknowledged': True}}, {'mapping': 'events', 'result': {'acknowledged': True}}, {'mapping': 'events_training_debug_image', 'result': {'acknowledged': True}}]
[2020-08-20 02:32:19,933] [8] [INFO] [trains.initialize] Applying mappings to ES host: [ConfigTree([('host', 'elasticsearch'), ('port', '9200')])]
[2020-08-20 02:32:20,022] [8] [INFO] [trains.initialize] [{'mapping': 'queue_metrics', 'result': {'acknowledged': True}}, {'mapping': 'worker_stats', 'result': {'acknowledged': True}}]
[2020-08-20 02:32:20,022] [8] [INFO] [trains.mongo.initialize.migration] Started mongodb migrations
[2020-08-20 02:32:20,026] [8] [INFO] [trains.mongo.initialize.migration] Finished mongodb migrations
[2020-08-20 02:32:20,125] [8] [INFO] [trains.server] Exposed Services: auth.create_credentials auth.create_user auth.edit_user auth.fixed_users_mode auth.get_credentials auth.get_token_for_user auth.login auth.logout auth.revoke_credentials auth.validate_token debug.ping events.add events.add_batch events.debug_images events.delete_for_task events.download_task_log events.get_multi_task_plots events.get_scalar_metric_data events.get_scalar_metrics_and_variants events.get_task_events events.get_task_latest_scalar_values events.get_task_log events.get_task_metrics events.get_task_plots events.get_vector_metrics_and_variants events.multi_task_scalar_metrics_iter_histogram events.scalar_metrics_iter_histogram events.vector_metrics_iter_histogram models.create models.delete models.edit models.get_all models.get_all_ex models.get_by_id models.get_by_task_id models.get_frameworks models.make_private models.make_public models.set_ready models.update models.update_for_task organization.get_tags projects.create projects.delete projects.get_all projects.get_all_ex projects.get_by_id projects.get_hyper_parameters projects.get_model_tags projects.get_task_tags projects.get_unique_metric_variants projects.make_private projects.make_public projects.update queues.add_task queues.create queues.delete queues.get_all queues.get_all_ex queues.get_by_id queues.get_default queues.get_next_task queues.get_queue_metrics queues.move_task_backward queues.move_task_forward queues.move_task_to_back queues.move_task_to_front queues.remove_task queues.update server.config server.endpoints server.get_stats server.info server.report_stats_option tasks.add_or_update_artifacts tasks.clone tasks.close tasks.completed tasks.create tasks.delete tasks.delete_configuration tasks.delete_hyper_params tasks.dequeue tasks.edit tasks.edit_configuration tasks.edit_hyper_params tasks.enqueue tasks.failed tasks.get_all tasks.get_all_ex tasks.get_by_id tasks.get_configuration_names tasks.get_configurations tasks.get_hyper_params tasks.get_types tasks.make_private tasks.make_public tasks.ping tasks.publish tasks.reset tasks.set_requirements tasks.started tasks.stop tasks.stopped tasks.update tasks.update_batch tasks.validate users.create users.delete users.get_all users.get_all_ex users.get_by_id users.get_current_user users.get_preferences users.set_preferences users.update workers.get_activity_report workers.get_all workers.get_metric_keys workers.get_stats workers.register workers.status_report workers.unregister
[2020-08-20 02:32:20,332] [8] [WARNING] [trains.service_repo] Returned 400 for users.get_preferences in 2ms, msg=Invalid user id: id=0cf9bd46c2af410f8a182a5c8b4d2b13, company=d1bd92a3b039400cbafc60a7a5b1e52b
[2020-08-20 02:32:20,370] [8] [WARNING] [trains.service_repo] Returned 400 for users.get_current_user in 4ms, msg=Invalid user (failed loading user)
[2020-08-20 02:32:20,374] [8] [INFO] [trains.service_repo] Returned 200 for projects.get_all_ex in 11ms
[2020-08-20 02:32:20,423] [8] [INFO] [trains.service_repo] Returned 200 for projects.get_all_ex in 22ms
[2020-08-20 02:32:20,446] [8] [INFO] [trains.service_repo] Returned 200 for tasks.get_all_ex in 37ms
[2020-08-20 02:32:20,698] [8] [INFO] [trains.service_repo] Returned 200 for auth.login in 9ms
[2020-08-20 02:32:20,717] [8] [INFO] [trains.service_repo] Returned 200 for queues.get_all in 3ms
[2020-08-20 02:32:20,725] [8] [INFO] [trains.service_repo] Returned 200 for workers.get_all in 1ms
[2020-08-20 02:32:20,731] [8] [INFO] [trains.service_repo] Returned 200 for workers.get_all in 1ms
[2020-08-20 02:32:20,738] [8] [INFO] [trains.service_repo] Returned 200 for workers.get_all in 1ms
[2020-08-20 02:32:20,745] [8] [INFO] [trains.service_repo] Returned 200 for workers.get_all in 1ms
[2020-08-20 02:32:20,763] [8] [INFO] [trains.service_repo] Returned 200 for queues.get_by_id in 3ms
[2020-08-20 02:32:20,777] [8] [INFO] [trains.service_repo] Returned 200 for workers.register in 7ms
[2020-08-20 02:32:20,842] [8] [INFO] [trains.service_repo] Returned 200 for queues.get_next_task in 51ms
[2020-08-20 02:32:23,833] [8] [INFO] [trains.service_repo] Returned 200 for workers.status_report in 21ms
[2020-08-20 02:32:25,867] [8] [INFO] [trains.service_repo] Returned 200 for queues.get_next_task in 13ms
[2020-08-20 02:32:30,889] [8] [INFO] [trains.service_repo] Returned 200 for queues.get_next_task in 10ms
[2020-08-20 02:32:35,910] [8] [INFO] [trains.service_repo] Returned 200 for queues.get_next_task in 10ms
[2020-08-20 02:32:40,931] [8] [INFO] [trains.service_repo] Returned 200 for queues.get_next_task in 10ms
[2020-08-20 02:32:42,249] [8] [INFO] [trains.service_repo] Returned 200 for auth.fixed_users_mode in 0ms
[2020-08-20 02:32:42,307] [8] [WARNING] [trains.service_repo] Returned 400 for users.get_preferences in 2ms, msg=Invalid user id: id=0cf9bd46c2af410f8a182a5c8b4d2b13, company=d1bd92a3b039400cbafc60a7a5b1e52b
[2020-08-20 02:32:42,618] [8] [WARNING] [trains.service_repo] Returned 400 for users.get_current_user in 3ms, msg=Invalid user (failed loading user)
[2020-08-20 02:32:42,682] [8] [INFO] [trains.service_repo] Returned 200 for projects.get_all_ex in 3ms
[2020-08-20 02:32:42,689] [8] [INFO] [trains.service_repo] Returned 200 for projects.get_all_ex in 14ms
[2020-08-20 02:32:42,882] [8] [INFO] [trains.service_repo] Returned 200 for tasks.get_all_ex in 12ms
[2020-08-20 02:32:45,948] [8] [INFO] [trains.service_repo] Returned 200 for queues.get_next_task in 10ms
[2020-08-20 02:32:50,971] [8] [INFO] [trains.service_repo] Returned 200 for queues.get_next_task in 12ms
[2020-08-20 02:32:54,070] [8] [INFO] [trains.service_repo] Returned 200 for workers.status_report in 19ms
[2020-08-20 02:32:55,994] [8] [INFO] [trains.service_repo] Returned 200 for queues.get_next_task in 11ms
[2020-08-20 02:33:01,015] [8] [INFO] [trains.service_repo] Returned 200 for queues.get_next_task in 10ms
```
The log says `GET http://elasticsearch:9200/_template/events*` was unsuccessful, but I can get the results on local and remote machines by entering `http://<ip_addr>:9200/_template/events*` in a web browser:
```
{"events_log":{"order":1,"index_patterns":["events-log-*"],"settings":{},"mappings":{"properties":{"msg":{"index":false,"type":"text"},"level":{"type":"keyword"}}},"aliases":{}},"events":{"order":0,"index_patterns":["events-*"],"settings":{"index":{"number_of_shards":"1"}},"mappings":{"_source":{"enabled":true},"properties":{"@timestamp":{"type":"date"},"task":{"type":"keyword"},"metric":{"type":"keyword"},"variant":{"type":"keyword"},"iter":{"type":"long"},"type":{"type":"keyword"},"worker":{"type":"keyword"},"value":{"type":"float"},"timestamp":{"type":"date"}}},"aliases":{}},"events_plot":{"order":1,"index_patterns":["events-plot-*"],"settings":{},"mappings":{"properties":{"plot_str":{"index":false,"type":"text"}}},"aliases":{}},"events_training_debug_image":{"order":1,"index_patterns":["events-training_debug_image-*"],"settings":{},"mappings":{"properties":{"key":{"type":"keyword"},"url":{"type":"keyword"}}},"aliases":{}}}
```

**Comment by jkhenning** [comment]
Hi @apwojcik,

> The log says GET http://elasticsearch:9200/_template/events* was unsuccessful, but I can get the results on local and remote machines by entering http://<ip_addr>:9200/_template/events* in a web browser:

These errors are transient and related to the time it takes the ElasticSearch docker image to initialize (the trains-apiserver simply keeps trying to communicate until it succeeds).

Your issue might be related to browser cache (assuming you're using the same browser as you did with the previous server, and you access the new server on the same host address) - if so, you can try removing all cookies, reloading the UI using `Ctrl-F5` and trying to login again.

If that doesn't help, can you please open your browser's developer tools panel, go to the Network tab and try reloading the UI (`Ctrl-F5`) - I assume some REST calls will return an error, and I'd like to see which ones 🙂

**Comment by apwojcik** [comment]
Hi @jkhenning,
Thank you for your help! Issue resolved  - after clearing browser cache, and cookies all started working as expected.
