### ISSUE TITLE
Issues with Worker Reading csv on Local Machine

### ISSUE THREAD

**Issue by gainesdg** [allegroai/trains#232]
I am currently trying to set up a worker to continually tune a Python model but I keep getting the error message: **trains_agent: ERROR: [WinError 2] The system cannot find the file specified** and it seems to me that this is linked to the worker being unable to read the csv file on the local machine. Is there anyway to work around this?

**Comment by bmartinn** [comment]
Hi @gainesdg 
Could you attach a full log of the `trains-agent` execution?
Could you also provide some information on the machine running `trains-agent` (OS python version,, docker, conda/pip etc.  and on the local machine created the original experiment ?

**Comment by ahmedgu2** [comment]
I have the same issue as well. My project is structured as following : 
 
├──data
        ├──raw
├──src
       ├──models

"raw" folder contains train.csv and test.csv and "models" folder contains .py file. The experiment runs without issues, but when set up a worker and enqueue the cloned experiment I get FileNotFoundError . It's maybe because the "data" folder and its containing is not pushed to git ? idk but it would be helpful to get an solution to it.
Here's the log : 


1604275701612 HP-Laptop:0 INFO task 2192e6bd169f47f8849decf07b294034 pulled from 7e500f7335cd4d0ea6a80ea2732e0b1f by worker HP-Laptop:0

1604275706835 HP-Laptop:0 DEBUG Current configuration (trains_agent v0.16.1, location: /tmp/.trains_agent.xz_41yar.cfg):
----------------------
api.version = 1.5
api.verify_certificate = true
api.default_version = 1.5
api.http.max_req_size = 15728640
api.http.retries.total = 240
api.http.retries.connect = 240
api.http.retries.read = 240
api.http.retries.redirect = 240
api.http.retries.status = 240
api.http.retries.backoff_factor = 1.0
api.http.retries.backoff_max = 120.0
api.http.wait_on_maintenance_forever = true
api.http.pool_maxsize = 512
api.http.pool_connections = 512
api.api_server = http://localhost:8008
api.web_server = http://localhost:8080
api.files_server = http://localhost:8081
api.credentials.access_key = **************
api.host = http://localhost:8008
sdk.storage.cache.default_base_dir = ~/.trains/cache
sdk.storage.cache.size.min_free_bytes = 10GB
sdk.storage.direct_access.0.url = file://*
sdk.metrics.file_history_size = 100
sdk.metrics.matplotlib_untitled_history_size = 100
sdk.metrics.images.format = JPEG
sdk.metrics.images.quality = 87
sdk.metrics.images.subsampling = 0
sdk.metrics.tensorboard_single_series_per_graph = false
sdk.network.metrics.file_upload_threads = 4
sdk.network.metrics.file_upload_starvation_warning_sec = 120
sdk.network.iteration.max_retries_on_server_error = 5
sdk.network.iteration.retry_backoff_factor_sec = 10
sdk.aws.s3.key = 
sdk.aws.s3.region = 
sdk.aws.boto3.pool_connections = 512
sdk.aws.boto3.max_multipart_concurrency = 16
sdk.log.null_log_propagate = false
sdk.log.task_log_buffer_capacity = 66
sdk.log.disable_urllib3_info = true
sdk.development.task_reuse_time_window_in_hours = 72.0
sdk.development.vcs_repo_detect_async = true
sdk.development.store_uncommitted_code_diff = true
sdk.development.support_stopping = true
sdk.development.default_output_uri = 
sdk.development.force_analyze_entire_repo = false
sdk.development.suppress_update_message = false
sdk.development.detect_with_pip_freeze = false
sdk.development.worker.report_period_sec = 2
sdk.development.worker.ping_period_sec = 30
sdk.development.worker.log_stdout = true
sdk.development.worker.report_global_mem_used = false
agent.worker_id = HP-Laptop:0
agent.worker_name = HP-Laptop
agent.force_git_ssh_protocol = false
agent.python_binary = 
agent.package_manager.type = pip
agent.package_manager.pip_version = <20.2
agent.package_manager.system_site_packages = false
agent.package_manager.force_upgrade = false
agent.package_manager.conda_channels.0 = defaults
agent.package_manager.conda_channels.1 = conda-forge
agent.package_manager.conda_channels.2 = pytorch
agent.package_manager.torch_nightly = false
agent.venvs_dir = /home/user/.trains/venvs-builds
agent.vcs_cache.enabled = true
agent.vcs_cache.path = /home/user/.trains/vcs-cache
agent.venv_update.enabled = false
agent.pip_download_cache.enabled = true
agent.pip_download_cache.path = /home/user/.trains/pip-download-cache
agent.translate_ssh = true
agent.reload_config = false
agent.docker_pip_cache = /home/user/.trains/pip-cache
agent.docker_apt_cache = /home/user/.trains/apt-cache
agent.docker_force_pull = false
agent.default_docker.image = nvidia/cuda:10.1-runtime-ubuntu18.04
agent.git_user = usergu2
agent.default_python = 3.7
agent.cuda_version = 100
agent.cudnn_version = 0
Executing task id [2192e6bd169f47f8849decf07b294034]:
repository = https://github.com/usergu2/project.git
branch = master
version_num = 8f5c4e2bb58de000d21b7d6901638a33f4667839
tag = 
entry_point = src/models/predict_model.py
working_dir = .
Using base prefix '/home/user/anaconda3'
New python executable in /home/user/.trains/venvs-builds/3.7/bin/python3.7
Also creating executable in /home/user/.trains/venvs-builds/3.7/bin/python
Installing setuptools, pip, wheel...

1604275711957 HP-Laptop:0 DEBUG done.
Using cached repository in "/home/user/.trains/vcs-cache/project.git.2a8ba6ab606e1dc19a731d24c3830c31/project.git"
Note: checking out '8f5c4e2bb58de000d21b7d6901638a33f4667839'.
You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.
If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:
  git checkout -b <new-branch-name>
HEAD is now at 8f5c4e2 hyperparam var declaration

1604275717716 HP-Laptop:0 DEBUG type: git
url: https://github.com/usergu2/project.git
branch: HEAD
commit: 8f5c4e2bb58de000d21b7d6901638a33f4667839
root: /home/user/.trains/venvs-builds/3.7/task_repository/project.git
Collecting pip<20.2
  Using cached pip-20.1.1-py2.py3-none-any.whl (1.5 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 20.2.4
    Uninstalling pip-20.2.4:
      Successfully uninstalled pip-20.2.4
Successfully installed pip-20.1.1
Collecting Cython
  Using cached Cython-0.29.21-cp37-cp37m-manylinux1_x86_64.whl (2.0 MB)
Installing collected packages: Cython
Successfully installed Cython-0.29.21
Requirement already satisfied: Cython==0.29.21 in /home/user/.trains/venvs-builds/3.7/lib/python3.7/site-packages (0.29.21)

1604275722802 HP-Laptop:0 DEBUG Collecting numpy==1.18.5
  Using cached numpy-1.18.5-cp37-cp37m-manylinux1_x86_64.whl (20.1 MB)
Installing collected packages: numpy
Successfully installed numpy-1.18.5

1604275727963 HP-Laptop:0 DEBUG Collecting attrs==20.2.0
  Using cached attrs-20.2.0-py2.py3-none-any.whl (48 kB)
Collecting boto3==1.15.1
  Using cached boto3-1.15.1-py2.py3-none-any.whl (129 kB)
Collecting botocore==1.18.18
  Using cached botocore-1.18.18-py2.py3-none-any.whl (6.7 MB)
Collecting catboost==0.16.2
  Using cached catboost-0.16.2-cp37-none-manylinux1_x86_64.whl (61.7 MB)
Collecting certifi==2020.6.20

1604275733636 HP-Laptop:0 DEBUG   Using cached certifi-2020.6.20-py2.py3-none-any.whl (156 kB)
Collecting chardet==3.0.4
  Using cached chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Collecting cycler==0.10.0
  Using cached cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)
Requirement already satisfied: Cython==0.29.21 in /home/user/.trains/venvs-builds/3.7/lib/python3.7/site-packages (from -r /tmp/cached-reqsfx9iy1qs.txt (line 8)) (0.29.21)
Collecting funcsigs==1.0.2
  Using cached funcsigs-1.0.2-py2.py3-none-any.whl (17 kB)
Collecting furl==2.1.0
  Using cached furl-2.1.0-py2.py3-none-any.whl (20 kB)
Processing /home/user/.cache/pip/wheels/56/b0/fe/4410d17b32f1f0c3cf54cdfb2bc04d7b4b8f4ae377e2229ba0/future-0.18.2-py3-none-any.whl
Collecting graphviz==0.14.2
  Using cached graphviz-0.14.2-py2.py3-none-any.whl (18 kB)
Collecting humanfriendly==8.2
  Using cached humanfriendly-8.2-py2.py3-none-any.whl (86 kB)
Collecting idna==2.10
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting importlib-metadata==2.0.0
  Using cached importlib_metadata-2.0.0-py2.py3-none-any.whl (31 kB)
Collecting jmespath==0.10.0
  Using cached jmespath-0.10.0-py2.py3-none-any.whl (24 kB)
Collecting joblib==0.17.0
  Using cached joblib-0.17.0-py3-none-any.whl (301 kB)
Collecting jsonschema==3.2.0
  Using cached jsonschema-3.2.0-py2.py3-none-any.whl (56 kB)
Collecting kiwisolver==1.2.0
  Using cached kiwisolver-1.2.0-cp37-cp37m-manylinux1_x86_64.whl (88 kB)

1604275738759 HP-Laptop:0 DEBUG Collecting matplotlib==3.3.2
  Using cached matplotlib-3.3.2-cp37-cp37m-manylinux1_x86_64.whl (11.6 MB)
Requirement already satisfied: numpy==1.18.5 in /home/user/.trains/venvs-builds/3.7/lib/python3.7/site-packages (from -r /tmp/cached-reqsfx9iy1qs.txt (line 21)) (1.18.5)
Collecting orderedmultidict==1.0.1
  Using cached orderedmultidict-1.0.1-py2.py3-none-any.whl (11 kB)
Collecting pandas==1.0.5
  Using cached pandas-1.0.5-cp37-cp37m-manylinux1_x86_64.whl (10.1 MB)
Collecting pathlib2==2.3.5
  Using cached pathlib2-2.3.5-py2.py3-none-any.whl (18 kB)
Collecting Pillow==8.0.1
  Using cached Pillow-8.0.1-cp37-cp37m-manylinux1_x86_64.whl (2.2 MB)
Collecting plotly==4.12.0
  Using cached plotly-4.12.0-py2.py3-none-any.whl (13.1 MB)

1604275744327 HP-Laptop:0 DEBUG Processing /home/user/.cache/pip/wheels/f0/4b/57/d037639271e326da3e80e0ddc37bd3d5da7bbf48b3173be557/psutil-5.7.3-cp37-cp37m-linux_x86_64.whl
Collecting PyJWT==1.7.1
  Using cached PyJWT-1.7.1-py2.py3-none-any.whl (18 kB)
Collecting pyparsing==2.4.7
  Using cached pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Processing /home/user/.cache/pip/wheels/a5/52/bf/71258a1d7b3c8cbe1ee53f9314c6f65f20385481eaee573cc5/pyrsistent-0.17.3-cp37-cp37m-linux_x86_64.whl
Collecting python-dateutil==2.8.1
  Using cached python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Collecting pytz==2020.1
  Using cached pytz-2020.1-py2.py3-none-any.whl (510 kB)
Processing /home/user/.cache/pip/wheels/5e/03/1e/e1e954795d6f35dfc7b637fe2277bff021303bd9570ecea653/PyYAML-5.3.1-cp37-cp37m-linux_x86_64.whl
Collecting requests==2.24.0
  Using cached requests-2.24.0-py2.py3-none-any.whl (61 kB)
Collecting requests-file==1.5.1
  Using cached requests_file-1.5.1-py2.py3-none-any.whl (3.7 kB)
Processing /home/user/.cache/pip/wheels/f9/8d/8d/f6af3f7f9eea3553bc2fe6d53e4b287dad18b06a861ac56ddf/retrying-1.3.3-py3-none-any.whl
Collecting s3transfer==0.3.3
  Using cached s3transfer-0.3.3-py2.py3-none-any.whl (69 kB)
Collecting scikit-learn==0.21.2
  Using cached scikit_learn-0.21.2-cp37-cp37m-manylinux1_x86_64.whl (6.7 MB)
Collecting scipy==1.5.3

1604275749791 HP-Laptop:0 DEBUG   Using cached scipy-1.5.3-cp37-cp37m-manylinux1_x86_64.whl (25.9 MB)
Collecting six==1.15.0
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting tqdm==4.51.0
  Using cached tqdm-4.51.0-py2.py3-none-any.whl (70 kB)
Collecting trains==0.16.2
  Using cached trains-0.16.2-py2.py3-none-any.whl (790 kB)
Collecting urllib3==1.25.11
  Using cached urllib3-1.25.11-py2.py3-none-any.whl (127 kB)
Collecting zipp==3.4.0
  Using cached zipp-3.4.0-py3-none-any.whl (5.2 kB)
Requirement already satisfied: setuptools in /home/user/.trains/venvs-builds/3.7/lib/python3.7/site-packages (from jsonschema==3.2.0->-r /tmp/cached-reqsfx9iy1qs.txt (line 18)) (50.3.2)
Installing collected packages: attrs, jmespath, six, python-dateutil, urllib3, botocore, s3transfer, boto3, graphviz, pyparsing, Pillow, certifi, kiwisolver, cycler, matplotlib, pytz, pandas, retrying, plotly, catboost, chardet, funcsigs, orderedmultidict, furl, future, humanfriendly, idna, zipp, importlib-metadata, joblib, pyrsistent, jsonschema, pathlib2, psutil, PyJWT, PyYAML, requests, requests-file, scipy, scikit-learn, tqdm, trains

1604275785609 HP-Laptop:0 DEBUG Successfully installed Pillow-8.0.1 PyJWT-1.7.1 PyYAML-5.3.1 attrs-20.2.0 boto3-1.15.1 botocore-1.18.18 catboost-0.16.2 certifi-2020.6.20 chardet-3.0.4 cycler-0.10.0 funcsigs-1.0.2 furl-2.1.0 future-0.18.2 graphviz-0.14.2 humanfriendly-8.2 idna-2.10 importlib-metadata-2.0.0 jmespath-0.10.0 joblib-0.17.0 jsonschema-3.2.0 kiwisolver-1.2.0 matplotlib-3.3.2 orderedmultidict-1.0.1 pandas-1.0.5 pathlib2-2.3.5 plotly-4.12.0 psutil-5.7.3 pyparsing-2.4.7 pyrsistent-0.17.3 python-dateutil-2.8.1 pytz-2020.1 requests-2.24.0 requests-file-1.5.1 retrying-1.3.3 s3transfer-0.3.3 scikit-learn-0.21.2 scipy-1.5.3 six-1.15.0 tqdm-4.51.0 trains-0.16.2 urllib3-1.25.11 zipp-3.4.0
Running task id [2192e6bd169f47f8849decf07b294034]:
[.]$ /home/user/.trains/venvs-builds/3.7/bin/python -u src/models/predict_model.py
Summary - installed python packages:
pip:
- attrs==20.2.0
- boto3==1.15.1
- botocore==1.18.18
- catboost==0.16.2
- certifi==2020.6.20
- chardet==3.0.4
- cycler==0.10.0
- Cython==0.29.21
- funcsigs==1.0.2
- furl==2.1.0
- future==0.18.2
- graphviz==0.14.2
- humanfriendly==8.2
- idna==2.10
- importlib-metadata==2.0.0
- jmespath==0.10.0
- joblib==0.17.0
- jsonschema==3.2.0
- kiwisolver==1.2.0
- matplotlib==3.3.2
- numpy==1.18.5
- orderedmultidict==1.0.1
- pandas==1.0.5
- pathlib2==2.3.5
- Pillow==8.0.1
- plotly==4.12.0
- psutil==5.7.3
- PyJWT==1.7.1
- pyparsing==2.4.7
- pyrsistent==0.17.3
- python-dateutil==2.8.1
- pytz==2020.1
- PyYAML==5.3.1
- requests==2.24.0
- requests-file==1.5.1
- retrying==1.3.3
- s3transfer==0.3.3
- scikit-learn==0.21.2
- scipy==1.5.3
- six==1.15.0
- tqdm==4.51.0
- trains==0.16.2
- urllib3==1.25.11
- zipp==3.4.0
Environment setup completed successfully
Starting Task Execution:

1604275790704 HP-Laptop:0 DEBUG TRAINS results page: http://localhost:8080/users/bfee6411a7ba47f78e793ae725373386/experiments/2192e6bd169f47f8849decf07b294034/output/log
Traceback (most recent call last):
  File "src/models/predict_model.py", line 31, in <module>
    train = pd.read_csv(f'{p}/data/raw/train.csv')
  File "/home/user/.trains/venvs-builds/3.7/lib/python3.7/site-packages/pandas/io/parsers.py", line 676, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/user/.trains/venvs-builds/3.7/lib/python3.7/site-packages/pandas/io/parsers.py", line 448, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/home/user/.trains/venvs-builds/3.7/lib/python3.7/site-packages/pandas/io/parsers.py", line 880, in __init__
    self._make_engine(self.engine)
  File "/home/user/.trains/venvs-builds/3.7/lib/python3.7/site-packages/pandas/io/parsers.py", line 1114, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/user/.trains/venvs-builds/3.7/lib/python3.7/site-packages/pandas/io/parsers.py", line 1891, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 374, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 674, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] File ./data/raw/train.csv does not exist: './data/raw/train.csv'

**Comment by bmartinn** [comment]
Hi @ahmedgu2 
> It's maybe because the "data" folder and its containing files is not pushed to git ? idk but it would be helpful to get a solution to this problem.

Yes exactly! The `trains-agent` will pull the code from the  git repo, since the data is not there, it is not accessible to the code.
I might have a quick solution, how about you upload the data as artifacts to a different Task, then use the artifacts to get a local copy.
[Step one](https://github.com/allegroai/events/blob/master/odsc20-east/generic/dataset_artifact.py), upload the dataset.
[Step Two](https://github.com/allegroai/events/blob/cea31fd9536213900157cf73837e6ae695a35f24/odsc20-east/generic/process_dataset.py#L21), get a a local copy of the data to process/train

What do you think?

**Comment by ahmedgu2** [comment]
Hi @bmartinn,
thank you for your answer.
Your solution works I guess, but wouldn't it be possible to make it somehow able to just directly point to data ( or some folder / files ) without the need of another task just for the sake of uploading datasets ?

**Comment by bmartinn** [comment]
@ahmedgu2 yes you are absolutely correct, and we are working on such a solution ;)
I'll update here, hopefully soon...

**Comment by patrickdasilva-clearml** [comment]
Hi @gainesdg , we're closing this issue as stale since it's been created too long ago. If you think the issue is still relevant, please make sure the issue persists on a recent version of ClearML (ideally the latest) before re-opening the issue. We'll gladly look at it again.
