### ISSUE TITLE
python2.7 ImportError: cannot import name timezone on 0.11.1

### ISSUE THREAD

**Issue by newwaylw** [allegroai/trains#47]
when use trains 0.11.1, we encountered an import error in python 2.7 environment:

```python
Python 2.7.15 |Anaconda, Inc.| (default, Nov 13 2018, 23:04:45) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import trains
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wei/anaconda3/envs/training/lib/python2.7/site-packages/trains/__init__.py", line 4, in <module>
    from .task import Task
  File "/home/wei/anaconda3/envs/training/lib/python2.7/site-packages/trains/task.py", line 14, in <module>
    from .binding.joblib_bind import PatchedJoblib
  File "/home/wei/anaconda3/envs/training/lib/python2.7/site-packages/trains/binding/joblib_bind.py", line 8, in <module>
    from ..binding.frameworks import _patched_call, _Empty, WeightsFileHandler
  File "/home/wei/anaconda3/envs/training/lib/python2.7/site-packages/trains/binding/frameworks/__init__.py", line 9, in <module>
    from ...model import InputModel, OutputModel
  File "/home/wei/anaconda3/envs/training/lib/python2.7/site-packages/trains/model.py", line 15, in <module>
    from .backend_interface.util import validate_dict, get_single_result, mutually_exclusive
  File "/home/wei/anaconda3/envs/training/lib/python2.7/site-packages/trains/backend_interface/__init__.py", line 2, in <module>
    from .task import Task
  File "/home/wei/anaconda3/envs/training/lib/python2.7/site-packages/trains/backend_interface/task/__init__.py", line 1, in <module>
    from .task import Task
  File "/home/wei/anaconda3/envs/training/lib/python2.7/site-packages/trains/backend_interface/task/task.py", line 21, in <module>
    from ..model import Model
  File "/home/wei/anaconda3/envs/training/lib/python2.7/site-packages/trains/backend_interface/model.py", line 12, in <module>
    from .util import make_message
  File "/home/wei/anaconda3/envs/training/lib/python2.7/site-packages/trains/backend_interface/util.py", line 4, in <module>
    from datetime import datetime, timezone
ImportError: cannot import name timezone

```
However, it is fine in 0.11.0

**Comment by bmartinn** [comment]
Hey @newwaylw thank you for catching it.
Fortunately we also caught this bug, so the fix is already scheduled to be release later today.
I'll update here once it is up :)

**Comment by bmartinn** [comment]
@newwaylw I just wanted to update here that v0.11.2 was released, fixing python 2.7 support.
Let me know if it solved the issue.

**Comment by newwaylw** [comment]
@bmartinn 
Thanks for the prompt fix!

**Comment by bmartinn** [comment]
:smiley:
