### ISSUE TITLE
get tasks data for multiple projects

### ISSUE THREAD

**Issue by bomri** [allegroai/trains#64]
I am trying to get tasks data for multiple projects using the following code:

```
from trains import Task

projects = ["project1",
            "project2",
            "project3",
            "project4",
            "project5",
            "project6",
            "project7"]

for project in projects:
    print(f"starting to process project: {project}")
    tasks = Task.get_tasks(project_name=project)
    # do some metedata process on tasks...
```

after getting few projects data, it crashes on something related to multiprocessing unable to open a new theard. This is the error I'm getting:

```
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 789, in __init__
    Pool.__init__(self, processes, initializer, initargs)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 174, in __init__
    self._repopulate_pool()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 239, in _repopulate_pool
    w.start()
  File "/usr/lib/python3.6/multiprocessing/dummy/__init__.py", line 48, in start
    threading.Thread.start(self)
  File "/usr/lib/python3.6/threading.py", line 846, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
```

Maybe the threads are not closed between each call to get_tasks?

**Comment by bmartinn** [comment]
Hi @bomri , is this the full exception trace back ?
The exception stack seems somewhat unrelated to trains...
How many project are you iterating over, and does it happen on the first loop iteration?

**Comment by bomri** [comment]
I'm iterating over ~10 projects. It doesn't happen on the first loop, first ones works fine.

Here is the full exception trace back:
```
Traceback (most recent call last):
  File "publish.py", line 17, in <module>
    tasks = Task.get_tasks(project_name=project)
  File "/home/ubuntu/allegro-venv/lib/python3.6/site-packages/trains/task.py", line 381, in get_tasks
    return cls.__get_tasks(task_ids=task_ids, project_name=project_name, task_name=task_name)
  File "/home/ubuntu/allegro-venv/lib/python3.6/site-packages/trains/task.py", line 1572, in __get_tasks
    return [cls(private=cls.__create_protection, task_id=task.id, log_to_backend=False) for task in res_tasks]
  File "/home/ubuntu/allegro-venv/lib/python3.6/site-packages/trains/task.py", line 1572, in <listcomp>
    return [cls(private=cls.__create_protection, task_id=task.id, log_to_backend=False) for task in res_tasks]
  File "/home/ubuntu/allegro-venv/lib/python3.6/site-packages/allegroai/task.py", line 39, in __init__
    super(Task, self).__init__(private=private, **kwargs)
  File "/home/ubuntu/allegro-venv/lib/python3.6/site-packages/trains/task.py", line 114, in __init__
    self._artifacts_manager = Artifacts(self)
  File "/home/ubuntu/allegro-venv/lib/python3.6/site-packages/trains/binding/artifacts.py", line 246, in __init__
    self._thread_pool = ThreadPool()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 789, in __init__
    Pool.__init__(self, processes, initializer, initargs)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 174, in __init__
    self._repopulate_pool()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 239, in _repopulate_pool
    w.start()
  File "/usr/lib/python3.6/multiprocessing/dummy/__init__.py", line 48, in start
    threading.Thread.start(self)
  File "/usr/lib/python3.6/threading.py", line 846, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
```

**Comment by bmartinn** [comment]
Thanks @bomri , with the full trace back, the issue was located :)
A new RC with a fix will be released shortly.

**Comment by bomri** [comment]
great, thanks @bmartinn for helping :)

**Comment by bmartinn** [comment]
Hi @bomri ,
Trains v0.12.2 was just released, it should solve the problem :)
`$ pip install trains==0.12.2`

**Comment by bomri** [comment]
Great! thanks @bmartinn
